#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

  # ===============================
  # = Mysql configurations
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3307/database?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: mysql
    password: mysql

  # ===============================
  # = Redis configurations
  # ===============================ß
  redis:
    database: 0
    host: 127.0.0.1
    port: 6380
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect